### ISSUE TITLE
F1

### ISSUE THREAD

**Issue by plancha2002** [xbc76/list#1]
Las claves de f1 estan desactualizadas aqui te dejo las vigentes: dazn f1 1080a acestream://ffaa5f556ee0497ad905208d317b1f3ed4c0914b
dazn f1 1080b
acestream://ffaa5f556ee0497ad905208d317b1f3ed4c0914b
dazn f1 720
acestream://a4d17dec3b341fb4c10afab81068dca29c5e9a4a
(source elcano.in)

**Comment by v4nHV** [comment]
gracias!

**Comment by plancha2002** [comment]
cree un fork mas modesto para tenerlo actualizado con el objetivo de compartirlo con familiares :), lo mantendre actualizado con elcano.in
